from django.db import models
from django.contrib.auth import get_user_model
from django.urls import reverse


class Country(models.Model):
    CONTINENT_CHOICES = [
        ("Africa", "Africa"),
        ("Aisa", "Asia"),
        ("Antarctica", "Antarctica"),
        ("Australia & Oceania", "Australia & Oceania"),
        ("Europe", "Europe"),
        ("North America", "North America"),
        ("South America", "South America"),
    ]
    LANG_CHOICES =[
        ("Chinese, Mandarin", "Chinese, Mandarin"),
        ("Spanish", "Spanish"),
        ("English", "English"),
        ("Bengali", "Bengali"),
        ("Hindi", "Hindi"),
        ("Portuguese", "Portuguese"),
        ("Russian", "Russian"),
        ("Japanese", "Japanese"),
        ("German, Standard", "German, Standard"),
        ("Chinese, Wu", "Chinese, Wu"),
        ("Javanese", "Javanese"),
        ("Korean", "Korean"),
        ("French", "French"),
        ("Vietnamese", "Vietnamese"),
        ("Telugu", "Telugu"),
        ("Chinese, Yue", "Chinese, Yue"),
        ("Marathi", "Marathi"),
        ("Tamil", "Tamil"),
        ("Turkish", "Turkish"),
        ("Urdu", "Urdu"),
        ("Chinese, Min Nan", "Chinese, Min Nan"),
        ("Chinese, Jinyu", "Chinese, Jinyu"),
        ("Gujarati", "Gujarati"),
        ("Polish", "Polish"),
        ("Arabic, Egyptian Spoken", "Arabic, Egyptian Spoken"),
        ("Ukrainian", "Ukrainian"),
        ("Italian", "Italian"),
        ("Chinese, Xiang", "Chinese, Xiang"),
        ("Malayalam", "Malayalam"),
        ("Chinese, Hakka", "Chinese, Hakka"),
        ("Kannada", "Kannada"),
        ("Oriya", "Oriya"),
        ("Panjabi, Western", "Panjabi, Western"),
        ("Sunda", "Sunda"),
        ("Panjabi, Eastern", "Panjabi, Eastern"),
        ("Romanian", "Romanian"),
        ("Bhojpuri", "Bhojpuri"),
        ("Azerbaijani, South", "Azerbaijani, South"),
        ("Farsi, Western", "Farsi, Western"),
        ("Maithili", "Maithili"),
        ("Hausa", "Hausa"),
        ("Arabic, Algerian Spoken", "Arabic, Algerian Spoken"),
        ("Burmese", "Burmese"),
        ("Serbo-Croatian", "Serbo-Croatian"),
        ("Chinese, Gan", "Chinese, Gan"),
        ("Awadhi", "Awadhi"),
        ("Thai", "Thai"),
        ("Dutch", "Dutch"),
        ("Yoruba", "Yoruba"),
        ("Sindhi", "Sindhi"),
        ("Arabic, Moroccan Spoken", "Arabic, Moroccan Spoken"),
        ("Arabic, Saidi Spoken", "Arabic, Saidi Spoken"),
        ("Uzbek, Northern", "Uzbek, Northern"),
        ("Malay", "Malay"),
        ("Amharic", "Amharic"),
        ("Indonesian", "Indonesian"),
        ("Igbo", "Igbo"),
        ("Tagalog", "Tagalog"),
        ("Nepali", "Nepali"),
        ("Arabic, Sudanese Spoken", "Arabic, Sudanese Spoken"),
        ("Saraiki", "Saraiki"),
        ("Cebuano", "Cebuano"),
        ("Arabic, North Levantine Spoken", "Arabic, North Levantine Spoken"),
        ("Thai, Northeastern", "Thai, Northeastern"),
        ("Assamese", "Assamese"),
        ("Hungarian", "Hungarian"),
        ("Chittagonian", "Chittagonian"),
        ("Arabic, Mesopotamian Spoken", "Arabic, Mesopotamian Spoken"),
        ("Madura", "Madura"),
        ("Sinhala", "Sinhala"),
        ("Haryanvi", "Haryanvi"),
        ("Marwari", "Marwari"),
        ("Czech", "Czech"),
        ("Greek", "Greek"),
        ("Magahi", "Magahi"),
        ("Chhattisgarhi", "Chhattisgarhi"),
        ("Deccan", "Deccan"),
        ("Chinese, Min Bei", "Chinese, Min Bei"),
        ("Belarusan", "Belarusan"),
        ("Zhuang, Northern", "Zhuang, Northern"),
        ("Arabic, Najdi Spoken", "Arabic, Najdi Spoken"),
        ("Pashto, Northern", "Pashto, Northern"),
        ("Somali", "Somali"),
        ("Malagasy", "Malagasy"),
        ("Arabic, Tunisian Spoken", "Arabic, Tunisian Spoken"),
        ("Rwanda", "Rwanda"),
        ("Zulu", "Zulu"),
        ("Bulgarian", "Bulgarian"),
        ("Swedish", "Swedish"),
        ("Lombard", "Lombard"),
        ("Oromo, West-Central", "Oromo, West-Central"),
        ("Pashto, Southern", "Pashto, Southern"),
        ("Kazakh", "Kazakh"),
        ("Ilocano", "Ilocano"),
        ("Tatar", "Tatar"),
        ("Fulfulde, Nigerian", "Fulfulde, Nigerian"),
        ("Arabic, Sanaani Spoken", "Arabic, Sanaani Spoken"),
        ("Uyghur", "Uyghur"),
        ("Haitian Creole French", "Haitian Creole French"),
        ("Azerbaijani, North", "Azerbaijani, North"),
        ("Napoletano-Calabrese", "Napoletano-Calabrese"),
        ("Khmer, Central", "Khmer, Central"),
        ("Farsi, Eastern", "Farsi, Eastern"),
        ("Akan", "Akan"),
        ("Hiligaynon", "Hiligaynon"),
        ("Kurmanji", "Kurmanji"),
        ("Shona", "Shona"),
    ]
    country = models.CharField(max_length=255)
    capital = models.CharField(max_length=255)
    continent = models.CharField(max_length=255, choices=CONTINENT_CHOICES, default="")
    lang = models.CharField(max_length=255, choices=LANG_CHOICES, default="")
    population = models.CharField(max_length=255)
    area = models.CharField(max_length=255)
    independence_day = models.DateField()
    author = models.ForeignKey(get_user_model(),on_delete=models.CASCADE)


    def __str__(self):
        return self.country

    class Meta:
        verbose_name_plural = 'countries'
